<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="wgybzb" name="zx.soft.utils.concurrent.WaiterTest" tests="15" failures="0" timestamp="17 Sep 2015 06:48:01 GMT" time="1.654" errors="0">
  <testcase name="shouldSupportSuccessiveResumeAwaits" time="0.001" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="waitShouldSupportResume" time="0.002" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="shouldSupportThreadWait0WithResumeCount" time="0.007" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="waitShouldSupportAssertionErrors" time="0.003" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="waitShouldSupportTimeouts" time="0.013" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="shouldSupportSuccessiveResumes" time="0.002" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="waitShouldSupportFail" time="0.002" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="shouldFailNullAssertionFromWorkerThreadWithReason" time="0.010" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="shouldFailNullAssertionWithReason" time="0.000" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="shouldSupportMultipleThreads" time="0.002" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="shouldHandleFailResumeAwait" time="0.401" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="shouldHandleResumesThenAwait" time="0.406" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="shouldSupportMultipleResumes" time="0.002" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="shouldHandleFailThenAwait" time="0.401" classname="zx.soft.utils.concurrent.WaiterTest"/>
  <testcase name="shouldHandleResumeFailAwait" time="0.402" classname="zx.soft.utils.concurrent.WaiterTest"/>
</testsuite> <!-- zx.soft.utils.concurrent.WaiterTest -->
